export const MEASUREMENT = {
  // Fetch actions
  FETCH_INIT   : 'MEASUREMENT__FETCH_INIT',
  FETCH_SUCCESS: 'MEASUREMENT__FETCH_SUCCESS',
  FETCH_FAILURE: 'MEASUREMENT__FETCH_FAILURE',
  FETCH_RESET  : 'MEASUREMENT__FETCH_RESET',
}
