export const EXERCISE = {
  // Fetch actions
  FETCH_INIT   : 'EXERCISE__FETCH_INIT',
  FETCH_SUCCESS: 'EXERCISE__FETCH_SUCCESS',
  FETCH_FAILURE: 'EXERCISE__FETCH_FAILURE',

  // Create actions
  CREATE_INIT   : 'EXERCISE__CREATE_INIT',
  CREATE_SUCCESS: 'EXERCISE__CREATE_SUCCESS',
  CREATE_FAILURE: 'EXERCISE__CREATE_FAILURE'
}
