export const WORKOUT = {
  // Fetch actions
  FETCH_INIT    : 'WORKOUT__FETCH_INIT',
  FETCH_SUCCESS : 'WORKOUT__FETCH_SUCCESS',
  FETCH_FAILURE : 'WORKOUT__FETCH_FAILURE',
  FETCH_CLEAR   : 'WORKOUT__FETCH_CLEAR',

  // Get actions
  GET_INIT      : 'WORKOUT__GET_INIT',
  GET_SUCCESS   : 'WORKOUT__GET_SUCCESS',
  GET_FAILURE   : 'WORKOUT__GET_FAILURE',

  // Delete actions
  DELETE_INIT   : 'WORKOUT__DELETE_INIT',
  DELETE_SUCCESS: 'WORKOUT__DELETE_SUCCESS',
  DELETE_FAILURE: 'WORKOUT__DELETE_FAILURE'
}
