export const WORKOUT = {
  // Fetch actions
  FETCH_INIT    : 'WORKOUT__FETCH_INIT',
  FETCH_SUCCESS : 'WORKOUT__FETCH_SUCCESS',

  // Get actions
  GET_INIT      : 'WORKOUT__GET_INIT',
  GET_SUCCESS   : 'WORKOUT__GET_SUCCESS',

  // Delete actions
  DELETE_INIT    : 'WORKOUT__DELETE_INIT',
  DELETE_SUCCESS : 'WORKOUT__DELETE_SUCCESS',
}
