export const WORKOUT = {
  // Fetch actions
  FETCH_INIT    : 'WORKOUT__FETCH_INIT',
  FETCH_SUCCESS : 'WORKOUT__FETCH_SUCCESS',

  DELETE_INIT    : 'WORKOUT__DELETE_INIT',
  DELETE_SUCCESS : 'WORKOUT__DELETE_SUCCESS',
}
